# Generated by Django 5.0.6 on 2024-05-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match_image',
            field=models.ImageField(blank=True, upload_to='match_image'),
        ),
    ]
