# Generated by Django 5.0.6 on 2024-05-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_date_ordered_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
