# Generated by Django 5.0.6 on 2024-06-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
