# Generated by Django 5.0.6 on 2024-06-02 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fixture_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='booked',
        ),
        migrations.CreateModel(
            name='BookedFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
            ],
        ),
    ]
