# Generated by Django 5.0.6 on 2024-06-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_fixture_booked_bookedfixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
