# Generated by Django 5.0.6 on 2024-06-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_bookedfixture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedfixture',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
